import { CSSProperties } from "react";

export const TOKEN = {
  bg: "var(--token-bg)",
  phone: "var(--token-phone)",
  text: "var(--token-text)",
  textSub: "var(--token-textSub)",
  textFaint: "var(--token-textFaint)",
  muted: "var(--token-muted)",
  dim: "var(--token-dim)",
  border: "var(--token-border)",
  borderSub: "var(--token-borderSub)",
  amber: "var(--token-amber)",
  amberText: "var(--token-amberText)",
  danger: "var(--token-danger)",
  success: "var(--token-success)",
  surface: "var(--token-surface)",
  surfaceElevated: "var(--token-surfaceElevated)",
  surfaceHighlight: "var(--token-surfaceHighlight)",
  mono: "'JetBrains Mono', monospace",
};

export const S: { [key: string]: CSSProperties } = {
  root: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    minHeight: "100vh",
    background: TOKEN.bg,
    padding: 16,
  },
  phone: {
    width: 312,
    maxWidth: "100%",
    background: TOKEN.phone,
    borderRadius: 42,
    border: `2px solid ${TOKEN.border}`,
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
    minHeight: 640,
    boxShadow: "0 40px 80px rgba(0,0,0,0.7)",
  },
  desktopContainer: {
    width: "100%",
    maxWidth: 1280,
    background: TOKEN.phone,
    borderRadius: 28,
    border: `1px solid ${TOKEN.border}`,
    overflow: "hidden",
    display: "flex",
    flexDirection: "row",
    height: "94vh",
    minHeight: 600,
    boxShadow: "0 24px 80px rgba(0,0,0,0.55), 0 0 0 1px rgba(255,255,255,0.03)",
  },
  sidebar: {
    width: 256,
    background: "rgba(10,10,18,0.82)",
    backdropFilter: "blur(24px)",
    borderRight: `1px solid rgba(255,255,255,0.04)`,
    display: "flex",
    flexDirection: "column",
    padding: "28px 12px",
    gap: 6,
    flexShrink: 0,
  },
  desktopContent: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    background: TOKEN.bg,
  },
  heroCard: {
    background: "linear-gradient(135deg, rgba(239,159,39,0.12) 0%, rgba(239,159,39,0.04) 60%, rgba(14,14,22,0.9) 100%)",
    borderRadius: 24,
    padding: "24px 20px",
    border: "1px solid rgba(239,159,39,0.18)",
    display: "flex",
    flexDirection: "column" as "column",
    gap: 8,
    position: "relative" as "relative",
    overflow: "hidden" as "hidden",
    boxShadow: "0 8px 32px rgba(239,159,39,0.08), 0 2px 8px rgba(0,0,0,0.3)",
  },
  statusBar: {
    background: TOKEN.phone,
    padding: "14px 22px 8px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    flexShrink: 0,
  },
  statusTime: { color: "#D8D6CE", fontSize: 12, fontWeight: 500, fontFamily: "monospace" },
  notch: { width: 80, height: 14, background: TOKEN.surface, borderRadius: 20, border: "0.5px solid #28283A" },
  homeBar: { padding: "8px 0 14px", display: "flex", justifyContent: "center", flexShrink: 0, background: TOKEN.phone },
  homeIndicator: { width: 100, height: 4, background: TOKEN.border, borderRadius: 2 },
  body: { flex: 1, overflow: "hidden", display: "flex", flexDirection: "column" },
  screen: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 24,
    padding: 24,
  },
  screenPad: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    padding: "20px 18px",
    overflowY: "auto" as "auto",
    gap: 12,
  },
  screenBase: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    overflowY: "auto" as "auto",
  },
  biometricBtn: {
    width: 84,
    height: 84,
    borderRadius: "50%",
    background: TOKEN.surface,
    border: `1.5px solid ${TOKEN.amber}`,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    outline: "none",
  },
  pinDot: {
    width: 44,
    height: 50,
    background: TOKEN.surface,
    borderRadius: 10,
    border: `0.5px solid ${TOKEN.border}`,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  lastSession: {
    padding: "10px 20px",
    background: TOKEN.surface,
    borderRadius: 20,
    border: `0.5px solid ${TOKEN.border}`,
  },
  popAnim: {
    animation: "pop 0.2s cubic-bezier(0.175, 0.885, 0.32, 1.275)",
  },
  rippleEffect: {
    position: "relative",
    overflow: "hidden",
  },
  pulseSuccess: {
    animation: "pulseSuccess 0.5s ease-out",
  },
  pulseError: {
    animation: "pulseError 0.5s ease-out",
  },
  biometricOverlay: {
    position: "absolute",
    inset: 0,
    background: "rgba(6, 6, 8, 0.95)",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 100,
    gap: 30,
    backdropFilter: "blur(8px)",
  },
  biometricRing: {
    width: 120,
    height: 120,
    borderRadius: "50%",
    border: `2px solid ${TOKEN.amber}`,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  biometricPulse: {
    position: "absolute",
    inset: -10,
    borderRadius: "50%",
    border: `1px solid ${TOKEN.amber}`,
    opacity: 0,
  },
  scanBar: {
    position: "absolute",
    width: "100%",
    height: 2,
    background: TOKEN.amber,
    top: "50%",
    left: 0,
    boxShadow: `0 0 15px ${TOKEN.amber}`,
  },
  row: { display: "flex", justifyContent: "space-between", alignItems: "center" },
  label: { color: TOKEN.muted, fontSize: 11 },
  heading: { color: TOKEN.text, fontSize: 18, fontWeight: 500 },
  iconBtn: {
    width: 34,
    height: 34,
    borderRadius: "50%",
    background: TOKEN.surface,
    border: `0.5px solid ${TOKEN.border}`,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    outline: "none",
  },
  todayBanner: {
    background: TOKEN.surface,
    borderRadius: 12,
    padding: "14px 16px",
    border: `0.5px solid ${TOKEN.border}`,
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  catGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: 10,
    flex: 1,
  },
  catBtn: {
    background: TOKEN.surfaceElevated,
    border: `0.5px solid ${TOKEN.borderSub}`,
    borderRadius: 14,
    padding: "14px 12px",
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: 8,
    cursor: "pointer",
    transition: "border-color 0.15s, background 0.15s",
    textAlign: "left",
  },
  picon: {
    width: 34,
    height: 34,
    borderRadius: 9,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  card: {
    background: TOKEN.surface,
    borderRadius: 18,
    padding: 16,
    border: `1px solid ${TOKEN.border}`,
    display: "flex",
    flexDirection: "column",
    gap: 4,
    transition: "border-color 0.2s",
  },
  cardRow: {
    background: TOKEN.surface,
    borderRadius: 12,
    padding: "11px 14px",
    border: `0.5px solid ${TOKEN.border}`,
    display: "flex",
    alignItems: "center",
    gap: 11,
    position: "relative",
    overflow: "hidden",
  },
  noteInput: {
    background: "transparent",
    border: "none",
    color: TOKEN.textSub,
    fontSize: 14,
    outline: "none",
    fontFamily: "inherit",
    width: "100%",
  },
  adjBtn: {
    width: 36,
    height: 36,
    borderRadius: "50%",
    background: TOKEN.surfaceHighlight,
    border: `0.5px solid ${TOKEN.borderSub}`,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    color: "#888",
    fontSize: 14,
    outline: "none",
  },
  fineBtn: {
    padding: "5px 12px",
    borderRadius: 20,
    background: TOKEN.surfaceHighlight,
    border: `0.5px solid ${TOKEN.borderSub}`,
    color: "#888",
    fontSize: 12,
    cursor: "pointer",
  },
  presetBtn: {
    padding: "7px 14px",
    borderRadius: 20,
    background: TOKEN.surfaceElevated,
    border: `0.5px solid ${TOKEN.borderSub}`,
    color: TOKEN.textFaint,
    fontSize: 12,
    cursor: "pointer",
    fontFamily: TOKEN.mono,
  },
  primaryBtn: {
    width: "100%",
    padding: 15,
    background: TOKEN.amber,
    border: "none",
    borderRadius: 14,
    color: TOKEN.amberText,
    fontSize: 15,
    fontWeight: 500,
    cursor: "pointer",
    letterSpacing: "0.02em",
  },
  tabRow: {
    display: "flex",
    background: TOKEN.surface,
    borderRadius: 10,
    padding: 3,
    gap: 2,
  },
  deleteSlide: {
    position: "absolute",
    right: 0,
    top: 0,
    bottom: 0,
    width: 64,
    background: TOKEN.danger,
    border: "none",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    fontSize: 20,
  },
  fab: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    background: `linear-gradient(135deg, #F5B93C 0%, ${TOKEN.amber} 100%)`,
    padding: "14px 32px",
    borderRadius: 30,
    border: "none",
    cursor: "pointer",
    boxShadow: "0 8px 28px rgba(239, 159, 39, 0.30)",
    transition: "transform 0.2s, box-shadow 0.2s",
  },
  toggle: {
    width: 40,
    height: 22,
    borderRadius: 11,
    border: "none",
    cursor: "pointer",
    position: "relative",
    flexShrink: 0,
  },
  knob: {
    width: 18,
    height: 18,
    borderRadius: "50%",
    background: "#fff",
    position: "absolute",
    top: 2,
    transition: "left 0.2s",
  },
  sectionLabel: {
    color: TOKEN.amber,
    fontSize: 11,
    fontWeight: 600,
    textTransform: "uppercase",
    letterSpacing: "0.1em",
    padding: "20px 20px 8px",
  },
  togRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "12px 20px",
    borderBottom: `0.5px solid ${TOKEN.borderSub}`,
  },
  menuItem: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "12px 20px",
    borderBottom: `0.5px solid ${TOKEN.borderSub}`,
    background: "none",
    border: "none",
    cursor: "pointer",
    width: "100%",
    outline: "none",
  },
  keypadGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: 16,
    width: "100%",
    maxWidth: 280,
    margin: "0 auto",
  },
  keyBtn: {
    height: 64,
    borderRadius: "50%",
    background: TOKEN.surface,
    border: `0.5px solid ${TOKEN.border}`,
    color: TOKEN.text,
    fontSize: 22,
    fontWeight: 500,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    outline: "none",
    transition: "background 0.2s, transform 0.1s",
  },
  shakeAnim: {
    animation: "shake 0.4s ease-in-out",
  },
  dangerBtn: {
    width: "100%",
    padding: 12,
    background: TOKEN.surfaceElevated,
    border: `0.5px solid ${TOKEN.border}`,
    borderRadius: 10,
    color: TOKEN.danger,
    fontSize: 13,
    cursor: "pointer",
  },
  successText: {
    color: TOKEN.success,
    fontSize: 14,
    fontWeight: 500,
    textAlign: "center",
    marginTop: 10,
  },
  forgotBtn: {
    background: "none",
    border: "none",
    color: TOKEN.dim,
    fontSize: 12,
    marginTop: 10,
    cursor: "pointer",
    textDecoration: "underline",
  },
  voiceBox: {
    background: TOKEN.surface,
    border: `1px solid ${TOKEN.border}`,
    borderRadius: 20,
    padding: "20px 16px",
    display: "flex",
    flexDirection: "column" as "column",
    alignItems: "center",
    gap: 12,
    width: "100%",
    marginBottom: 8,
  },
  voiceRing: {
    width: 80,
    height: 80,
    borderRadius: "50%",
    border: `2px solid ${TOKEN.amber}`,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    transition: "background 0.3s",
  },
  voiceResult: {
    background: TOKEN.surfaceElevated,
    borderRadius: 12,
    padding: "12px 16px",
    width: "100%",
    textAlign: "center" as "center",
    border: `1px solid ${TOKEN.border}`,
    display: "flex",
    flexDirection: "column" as "column",
    gap: 4,
  },
  confirmBtn: {
    width: "100%",
    padding: "12px",
    background: TOKEN.amber,
    border: "none",
    borderRadius: 12,
    color: TOKEN.amberText,
    fontSize: 14,
    fontWeight: 600,
    cursor: "pointer",
    letterSpacing: "0.02em",
  },
  lockHeader: {
    textAlign: "center",
    display: "flex",
    flexDirection: "column",
    gap: 4,
  },
  lockSubtitle: {
    fontSize: 10,
    letterSpacing: "0.25em",
    color: TOKEN.muted,
    textTransform: "uppercase",
    fontWeight: 500,
    opacity: 0.8,
  },
  lockTitle: {
    fontSize: 36,
    fontWeight: 700,
    color: TOKEN.text,
    letterSpacing: "0.05em",
  },
  biometricCircle: {
    width: 140,
    height: 140,
    borderRadius: "50%",
    border: `1.5px solid ${TOKEN.amber}`,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    margin: "20px 0",
    position: "relative",
  },
  instructionText: {
    textAlign: "center",
    display: "flex",
    flexDirection: "column",
    gap: 6,
  },
  unlockText: {
    fontSize: 18,
    fontWeight: 600,
    color: TOKEN.text,
  },
  pinHint: {
    fontSize: 14,
    color: TOKEN.dim,
  },
  pinRow: {
    display: "flex",
    gap: 12,
    justifyContent: "center",
    marginTop: 10,
  },
  pinSquare: {
    width: 48,
    height: 54,
    borderRadius: 12,
    background: TOKEN.surfaceHighlight,
    border: `1px solid ${TOKEN.border}`,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    transition: "all 0.2s",
  },
  pinCircle: {
    width: 6,
    height: 6,
    borderRadius: "50%",
    background: TOKEN.dim,
    transition: "all 0.2s",
  },
  pinCircleFilled: {
    background: TOKEN.amber,
    transform: "scale(1.5)",
    boxShadow: `0 0 10px ${TOKEN.amber}60`,
  },
  lockFooter: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 20,
    marginTop: "auto",
    paddingBottom: 20,
    width: "100%",
  },
  footerBtn: {
    width: 54,
    height: 54,
    borderRadius: "50%",
    background: TOKEN.surfaceHighlight,
    border: `1px solid ${TOKEN.border}`,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    color: TOKEN.text,
  },
  sessionSummary: {
    padding: "8px 16px",
    background: TOKEN.surfaceHighlight,
    borderRadius: 20,
    border: `1px solid ${TOKEN.border}`,
    fontSize: 12,
    color: TOKEN.muted,
    display: "flex",
    alignItems: "center",
    gap: 6,
  },
  reportGrid: {
    display: "flex",
    flexDirection: "column",
    gap: 16,
    padding: "0 4px 40px",
  },
  reportCard: {
    background: TOKEN.surface,
    borderRadius: 24,
    padding: 20,
    border: `1px solid ${TOKEN.border}`,
    display: "flex",
    flexDirection: "column",
    gap: 12,
  },
  insightItem: {
    background: "rgba(255,255,255,0.03)",
    borderRadius: 16,
    padding: "12px 16px",
    display: "flex",
    gap: 12,
    alignItems: "center",
  },
  insightIcon: {
    width: 32,
    height: 32,
    borderRadius: "50%",
    background: "rgba(239, 159, 39, 0.1)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: TOKEN.amber,
    fontSize: 14,
  },
  heatmapGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(7, 1fr)",
    gap: 4,
    marginTop: 8,
  },
  heatmapCell: {
    aspectRatio: "1/1",
    borderRadius: 3,
    background: TOKEN.surfaceHighlight,
  },
  reportMetric: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
  },
  metricLabel: {
    fontSize: 12,
    color: TOKEN.muted,
  },
  metricValue: {
    fontSize: 24,
    fontWeight: 600,
    color: TOKEN.text,
    fontFamily: TOKEN.mono,
  },
  tabNav: {
    display: "flex",
    background: "rgba(12, 12, 20, 0.88)",
    backdropFilter: "blur(24px)",
    WebkitBackdropFilter: "blur(24px)",
    padding: "10px 12px 28px",
    borderRadius: "24px 24px 0 0",
    gap: 4,
    marginTop: "auto",
    borderTop: `1px solid rgba(255,255,255,0.05)`,
    zIndex: 50,
    boxShadow: "0 -8px 32px rgba(0,0,0,0.3)",
  },
  tabItem: {
    flex: 1,
    padding: "8px",
    borderRadius: 16,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 4,
    cursor: "pointer",
    transition: "all 0.2s",
  },
  walletGrid: {
    display: "flex",
    gap: 12,
    overflowX: "auto" as "auto",
    padding: "4px 0 12px",
    msOverflowStyle: "none",
    scrollbarWidth: "none",
  },
  walletCard: {
    minWidth: 120,
    background: TOKEN.surface,
    borderRadius: 16,
    padding: 14,
    border: `1px solid ${TOKEN.border}`,
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  walletTag: {
    fontSize: 10,
    padding: "3px 8px",
    borderRadius: 6,
    background: TOKEN.surfaceHighlight,
    color: TOKEN.muted,
    fontWeight: 600,
    textTransform: "uppercase",
  },
  recurringToggle: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "12px 16px",
    background: TOKEN.surface,
    borderRadius: 14,
    border: `1px solid ${TOKEN.border}`,
    marginTop: 10,
  },
  subItem: {
    background: TOKEN.surface,
    borderRadius: 16,
    padding: 16,
    border: `1px solid ${TOKEN.border}`,
    display: "flex",
    alignItems: "center",
    gap: 12,
  },
  healthRing: {
    width: 80,
    height: 80,
    borderRadius: "50%",
    border: `6px solid ${TOKEN.surfaceHighlight}`,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 20,
    fontWeight: 700,
    color: TOKEN.amber,
  },
  progressBarContainer: {
    height: 6,
    background: TOKEN.surfaceHighlight,
    borderRadius: 3,
    overflow: "hidden",
    marginTop: 4,
  },
  progressBar: {
    height: "100%",
    borderRadius: 3,
    transition: "width 0.5s ease-out",
  },
  calendarGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(7, 1fr)",
    gap: 1,
    background: TOKEN.border,
    border: `0.5px solid ${TOKEN.border}`,
    borderRadius: 12,
    overflow: "hidden",
    marginTop: 10,
  },
  calendarDay: {
    background: TOKEN.bg,
    aspectRatio: "1/1",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    padding: 4,
    gap: 2,
  },
  merchantItem: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "10px 0",
    borderBottom: `0.5px solid ${TOKEN.border}`,
  },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: "50%",
    background: TOKEN.surfaceHighlight,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    border: `2px solid ${TOKEN.border}`,
    cursor: "pointer",
  },
  avatarImg: {
    width: "100%",
    height: "100%",
    objectFit: "cover" as "cover",
  },
};
